version: '3'

services:
    postgres:
        restart: always
        image: postgres:latest
        container_name: {{cookiecutter.db_host}}
        environment:
            POSTGRES_PASSWORD: password
            POSTGRES_USER: {{cookiecutter.db_user}}
            POSTGRES_DB: {{cookiecutter.db_name}}
            POSTGRES_INITDB_ARGS: --data-checksums --auth-local trust
            PGDATA: /var/lib/postgresql/data/pgdata
#        env_file: .env
        ports:
            - "5432:5432"
        volumes:
            - "docker-db-volume:/var/lib/postgresql/data"
        networks:
          - aiohttp

    {{cookiecutter.app_name}}:
        restart: always
        build:
            context: .
        ports:
            - "{{cookiecutter.server_port}}:{{cookiecutter.server_port}}"
#        env_file: .env
        environment:
            DB_HOST: postgres
            DB_PORT: 5432
            DB_NAME: postgres
            DB_USER: postgres
            DB_SCHEMA: public
            DB_PASSWORD: password
        depends_on:
            - postgres
        links:
            - postgres
        networks:
            - aiohttp

volumes:
    docker-db-volume:
        driver: local

networks:
    aiohttp:
